//
//  Country.swift
//  Chat
//
//  Created by Vadim Koronchik on 5/4/19.
//  Copyright © 2019 Vadim Koronchik. All rights reserved.
//

import Foundation

struct Country {
    var code: String
    var name: String
    var phoneCode: UInt64
}

let allCountries: [Country] = [
    Country(code: "PH", name: "Philippines", phoneCode: 63),
    Country(code: "CK", name: "Cook Islands", phoneCode: 682),
    Country(code: "PG", name: "Papua New Guinea", phoneCode: 675),
    Country(code: "BJ", name: "Benin", phoneCode: 229),
    Country(code: "UA", name: "Ukraine", phoneCode: 380),
    Country(code: "IR", name: "Iran", phoneCode: 98),
    Country(code: "EC", name: "Ecuador", phoneCode: 593),
    Country(code: "GD", name: "Grenada", phoneCode: 1),
    Country(code: "PE", name: "Peru", phoneCode: 51),
    Country(code: "PK", name: "Pakistan", phoneCode: 92),
    Country(code: "SK", name: "Slovakia", phoneCode: 421),
    Country(code: "GQ", name: "Equatorial Guinea", phoneCode: 240),
    Country(code: "EH", name: "Western Sahara", phoneCode: 212),
    Country(code: "PR", name: "Puerto Rico", phoneCode: 1),
    Country(code: "ME", name: "Montenegro", phoneCode: 382),
    Country(code: "MC", name: "Monaco", phoneCode: 377),
    Country(code: "RU", name: "Russia", phoneCode: 7),
    Country(code: "DJ", name: "Djibouti", phoneCode: 253),
    Country(code: "NR", name: "Nauru", phoneCode: 674),
    Country(code: "MS", name: "Montserrat", phoneCode: 1),
    Country(code: "SX", name: "Sint Maarten", phoneCode: 1),
    Country(code: "LC", name: "Saint Lucia", phoneCode: 1),
    Country(code: "MM", name: "Myanmar", phoneCode: 95),
    Country(code: "AZ", name: "Azerbaijan", phoneCode: 994),
    Country(code: "SL", name: "Sierra Leone", phoneCode: 232),
    Country(code: "NO", name: "Norway", phoneCode: 47),
    Country(code: "KM", name: "Comoros", phoneCode: 269),
    Country(code: "IQ", name: "Iraq", phoneCode: 964),
    Country(code: "BZ", name: "Belize", phoneCode: 501),
    Country(code: "UZ", name: "Uzbekistan", phoneCode: 998),
    Country(code: "TM", name: "Turkmenistan", phoneCode: 993),
    Country(code: "ZA", name: "South Africa", phoneCode: 27),
    Country(code: "TZ", name: "Tanzania", phoneCode: 255),
    Country(code: "AW", name: "Aruba", phoneCode: 297),
    Country(code: "KG", name: "Kyrgyzstan", phoneCode: 996),
    Country(code: "IO", name: "British Indian Ocean Territory", phoneCode: 246),
    Country(code: "HU", name: "Hungary", phoneCode: 36),
    Country(code: "MR", name: "Mauritania", phoneCode: 222),
    Country(code: "SR", name: "Suriname", phoneCode: 597),
    Country(code: "NL", name: "Netherlands", phoneCode: 31),
    Country(code: "KW", name: "Kuwait", phoneCode: 965),
    Country(code: "RW", name: "Rwanda", phoneCode: 250),
    Country(code: "GA", name: "Gabon", phoneCode: 241),
    Country(code: "AI", name: "Anguilla", phoneCode: 1),
    Country(code: "SV", name: "El Salvador", phoneCode: 503),
    Country(code: "GE", name: "Georgia", phoneCode: 995),
    Country(code: "FR", name: "France", phoneCode: 33),
    Country(code: "FI", name: "Finland", phoneCode: 358),
    Country(code: "NZ", name: "New Zealand", phoneCode: 64),
    Country(code: "BD", name: "Bangladesh", phoneCode: 880),
    Country(code: "WS", name: "Samoa", phoneCode: 685),
    Country(code: "SB", name: "Solomon Islands", phoneCode: 677),
    Country(code: "JM", name: "Jamaica", phoneCode: 1),
    Country(code: "BA", name: "Bosnia and Herzegovina", phoneCode: 387),
    Country(code: "MP", name: "Northern Mariana Islands", phoneCode: 1),
    Country(code: "RS", name: "Serbia", phoneCode: 381),
    Country(code: "ZM", name: "Zambia", phoneCode: 260),
    Country(code: "CR", name: "Costa Rica", phoneCode: 506),
    Country(code: "TG", name: "Togo", phoneCode: 228),
    Country(code: "BN", name: "Brunei", phoneCode: 673),
    Country(code: "LA", name: "Laos", phoneCode: 856),
    Country(code: "CU", name: "Cuba", phoneCode: 53),
    Country(code: "GT", name: "Guatemala", phoneCode: 502),
    Country(code: "EG", name: "Egypt", phoneCode: 20),
    Country(code: "BM", name: "Bermuda", phoneCode: 1),
    Country(code: "SA", name: "Saudi Arabia", phoneCode: 966),
    Country(code: "CG", name: "Republic of the Congo", phoneCode: 242),
    Country(code: "FO", name: "Faroe Islands", phoneCode: 298),
    Country(code: "ML", name: "Mali", phoneCode: 223),
    Country(code: "TH", name: "Thailand", phoneCode: 66),
    Country(code: "OM", name: "Oman", phoneCode: 968),
    Country(code: "TL", name: "East Timor", phoneCode: 670),
    Country(code: "BB", name: "Barbados", phoneCode: 1),
    Country(code: "CW", name: "Curacao", phoneCode: 599),
    Country(code: "GY", name: "Guyana", phoneCode: 592),
    Country(code: "AS", name: "American Samoa", phoneCode: 1),
    Country(code: "LI", name: "Liechtenstein", phoneCode: 423),
    Country(code: "TO", name: "Tonga", phoneCode: 676),
    Country(code: "PL", name: "Poland", phoneCode: 48),
    Country(code: "IS", name: "Iceland", phoneCode: 354),
    Country(code: "ID", name: "Indonesia", phoneCode: 62),
    Country(code: "TD", name: "Chad", phoneCode: 235),
    Country(code: "BY", name: "Belarus", phoneCode: 375),
    Country(code: "SI", name: "Slovenia", phoneCode: 386),
    Country(code: "CX", name: "Christmas Island", phoneCode: 61),
    Country(code: "FM", name: "Micronesia", phoneCode: 691),
    Country(code: "TR", name: "Turkey", phoneCode: 90),
    Country(code: "SD", name: "Sudan", phoneCode: 249),
    Country(code: "TK", name: "Tokelau", phoneCode: 690),
    Country(code: "BS", name: "Bahamas", phoneCode: 1),
    Country(code: "VE", name: "Venezuela", phoneCode: 58),
    Country(code: "AD", name: "Andorra", phoneCode: 376),
    Country(code: "MK", name: "Macedonia", phoneCode: 389),
    Country(code: "IM", name: "Isle of Man", phoneCode: 44),
    Country(code: "KP", name: "North Korea", phoneCode: 850),
    Country(code: "CO", name: "Colombia", phoneCode: 57),
    Country(code: "UG", name: "Uganda", phoneCode: 256),
    Country(code: "LV", name: "Latvia", phoneCode: 371),
    Country(code: "GG", name: "Guernsey", phoneCode: 44),
    Country(code: "VN", name: "Vietnam", phoneCode: 84),
    Country(code: "CD", name: "Democratic Republic of the Congo", phoneCode: 243),
    Country(code: "DO", name: "Dominican Republic", phoneCode: 1),
    Country(code: "MD", name: "Moldova", phoneCode: 373),
    Country(code: "NG", name: "Nigeria", phoneCode: 234),
    Country(code: "BR", name: "Brazil", phoneCode: 55),
    Country(code: "JO", name: "Jordan", phoneCode: 962),
    Country(code: "BE", name: "Belgium", phoneCode: 32),
    Country(code: "GL", name: "Greenland", phoneCode: 299),
    Country(code: "KZ", name: "Kazakhstan", phoneCode: 7),
    Country(code: "BO", name: "Bolivia", phoneCode: 591),
    Country(code: "GI", name: "Gibraltar", phoneCode: 350),
    Country(code: "LY", name: "Libya", phoneCode: 218),
    Country(code: "US", name: "United States", phoneCode: 1),
    Country(code: "CZ", name: "Czech Republic", phoneCode: 420),
    Country(code: "BQ", name: "Bonaire, Saint Eustatius and Saba ", phoneCode: 599),
    Country(code: "AL", name: "Albania", phoneCode: 355),
    Country(code: "BH", name: "Bahrain", phoneCode: 973),
    Country(code: "TT", name: "Trinidad and Tobago", phoneCode: 1),
    Country(code: "PY", name: "Paraguay", phoneCode: 595),
    Country(code: "DE", name: "Germany", phoneCode: 49),
    Country(code: "NA", name: "Namibia", phoneCode: 264),
    Country(code: "AG", name: "Antigua and Barbuda", phoneCode: 1),
    Country(code: "UY", name: "Uruguay", phoneCode: 598),
    Country(code: "AT", name: "Austria", phoneCode: 43),
    Country(code: "GF", name: "French Guiana", phoneCode: 594),
    Country(code: "MV", name: "Maldives", phoneCode: 960),
    Country(code: "GU", name: "Guam", phoneCode: 1),
    Country(code: "LB", name: "Lebanon", phoneCode: 961),
    Country(code: "LK", name: "Sri Lanka", phoneCode: 94),
    Country(code: "CI", name: "Ivory Coast", phoneCode: 225),
    Country(code: "BG", name: "Bulgaria", phoneCode: 359),
    Country(code: "MT", name: "Malta", phoneCode: 356),
    Country(code: "MY", name: "Malaysia", phoneCode: 60),
    Country(code: "AE", name: "United Arab Emirates", phoneCode: 971),
    Country(code: "CH", name: "Switzerland", phoneCode: 41),
    Country(code: "PS", name: "Palestinian Territory", phoneCode: 970),
    Country(code: "SS", name: "South Sudan", phoneCode: 211),
    Country(code: "PA", name: "Panama", phoneCode: 507),
    Country(code: "IE", name: "Ireland", phoneCode: 353),
    Country(code: "KR", name: "South Korea", phoneCode: 82),
    Country(code: "ES", name: "Spain", phoneCode: 34),
    Country(code: "TC", name: "Turks and Caicos Islands", phoneCode: 1),
    Country(code: "BT", name: "Bhutan", phoneCode: 975),
    Country(code: "CC", name: "Cocos Islands", phoneCode: 61),
    Country(code: "DK", name: "Denmark", phoneCode: 45),
    Country(code: "TW", name: "Taiwan", phoneCode: 886),
    Country(code: "JP", name: "Japan", phoneCode: 81),
    Country(code: "MW", name: "Malawi", phoneCode: 265),
    Country(code: "EE", name: "Estonia", phoneCode: 372),
    Country(code: "VI", name: "U.S. Virgin Islands", phoneCode: 1),
    Country(code: "SE", name: "Sweden", phoneCode: 46),
    Country(code: "VU", name: "Vanuatu", phoneCode: 678),
    Country(code: "MG", name: "Madagascar", phoneCode: 261),
    Country(code: "GM", name: "Gambia", phoneCode: 220),
    Country(code: "FJ", name: "Fiji", phoneCode: 679),
    Country(code: "MX", name: "Mexico", phoneCode: 52),
    Country(code: "KH", name: "Cambodia", phoneCode: 855),
    Country(code: "NI", name: "Nicaragua", phoneCode: 505),
    Country(code: "TV", name: "Tuvalu", phoneCode: 688),
    Country(code: "ER", name: "Eritrea", phoneCode: 291),
    Country(code: "BI", name: "Burundi", phoneCode: 257),
    Country(code: "NF", name: "Norfolk Island", phoneCode: 672),
    Country(code: "IN", name: "India", phoneCode: 91),
    Country(code: "MU", name: "Mauritius", phoneCode: 230),
    Country(code: "HT", name: "Haiti", phoneCode: 509),
    Country(code: "VC", name: "Saint Vincent and the Grenadines", phoneCode: 1),
    Country(code: "LS", name: "Lesotho", phoneCode: 266),
    Country(code: "TJ", name: "Tajikistan", phoneCode: 992),
    Country(code: "FK", name: "Falkland Islands", phoneCode: 500),
    Country(code: "SN", name: "Senegal", phoneCode: 221),
    Country(code: "GW", name: "Guinea-Bissau", phoneCode: 245),
    Country(code: "HK", name: "Hong Kong", phoneCode: 852),
    Country(code: "BW", name: "Botswana", phoneCode: 267),
    Country(code: "PW", name: "Palau", phoneCode: 680),
    Country(code: "SM", name: "San Marino", phoneCode: 378),
    Country(code: "XK", name: "Kosovo", phoneCode: 383),
    Country(code: "MA", name: "Morocco", phoneCode: 212),
    Country(code: "KE", name: "Kenya", phoneCode: 254),
    Country(code: "IL", name: "Israel", phoneCode: 972),
    Country(code: "CA", name: "Canada", phoneCode: 1),
    Country(code: "HR", name: "Croatia", phoneCode: 385),
    Country(code: "CM", name: "Cameroon", phoneCode: 237),
    Country(code: "AX", name: "Aland Islands", phoneCode: 358),
    Country(code: "MH", name: "Marshall Islands", phoneCode: 692),
    Country(code: "CL", name: "Chile", phoneCode: 56),
    Country(code: "KY", name: "Cayman Islands", phoneCode: 1),
    Country(code: "BF", name: "Burkina Faso", phoneCode: 226),
    Country(code: "VA", name: "Vatican", phoneCode: 39),
    Country(code: "GH", name: "Ghana", phoneCode: 233),
    Country(code: "SG", name: "Singapore", phoneCode: 65),
    Country(code: "CN", name: "China", phoneCode: 86),
    Country(code: "JE", name: "Jersey", phoneCode: 44),
    Country(code: "ZW", name: "Zimbabwe", phoneCode: 263),
    Country(code: "DM", name: "Dominica", phoneCode: 1),
    Country(code: "LR", name: "Liberia", phoneCode: 231),
    Country(code: "AR", name: "Argentina", phoneCode: 54),
    Country(code: "CV", name: "Cape Verde", phoneCode: 238),
    Country(code: "SC", name: "Seychelles", phoneCode: 248),
    Country(code: "LU", name: "Luxembourg", phoneCode: 352),
    Country(code: "AF", name: "Afghanistan", phoneCode: 93),
    Country(code: "MO", name: "Macao", phoneCode: 853),
    Country(code: "SO", name: "Somalia", phoneCode: 252),
    Country(code: "AO", name: "Angola", phoneCode: 244),
    Country(code: "LT", name: "Lithuania", phoneCode: 370),
    Country(code: "IT", name: "Italy", phoneCode: 39),
    Country(code: "VG", name: "British Virgin Islands", phoneCode: 1),
    Country(code: "TN", name: "Tunisia", phoneCode: 216),
    Country(code: "QA", name: "Qatar", phoneCode: 974),
    Country(code: "MN", name: "Mongolia", phoneCode: 976),
    Country(code: "GB", name: "United Kingdom", phoneCode: 44),
    Country(code: "AU", name: "Australia", phoneCode: 61),
    Country(code: "AM", name: "Armenia", phoneCode: 374),
    Country(code: "KN", name: "Saint Kitts and Nevis", phoneCode: 1),
    Country(code: "NP", name: "Nepal", phoneCode: 977),
    Country(code: "YE", name: "Yemen", phoneCode: 967),
    Country(code: "KI", name: "Kiribati", phoneCode: 686),
    Country(code: "ST", name: "Sao Tome and Principe", phoneCode: 239),
    Country(code: "NU", name: "Niue", phoneCode: 683),
    Country(code: "RO", name: "Romania", phoneCode: 40),
    Country(code: "CF", name: "Central African Republic", phoneCode: 236),
    Country(code: "MQ", name: "Martinique", phoneCode: 596),
    Country(code: "DZ", name: "Algeria", phoneCode: 213),
    Country(code: "NE", name: "Niger", phoneCode: 227),
    Country(code: "SY", name: "Syria", phoneCode: 963),
    Country(code: "CY", name: "Cyprus", phoneCode: 357),
    Country(code: "GR", name: "Greece", phoneCode: 30),
    Country(code: "MZ", name: "Mozambique", phoneCode: 258),
    Country(code: "HN", name: "Honduras", phoneCode: 504),
    Country(code: "SZ", name: "Swaziland", phoneCode: 268),
    Country(code: "GN", name: "Guinea", phoneCode: 224),
    Country(code: "ET", name: "Ethiopia", phoneCode: 251),
    Country(code: "PT", name: "Portugal", phoneCode: 351)
]
